### ISSUE TITLE
[Feature] Update to PHPUnit 10's Event System

### ISSUE THREAD

**Issue by paulbalandan** [NexusPHP/tachycardia#11]
**Is your feature request related to a problem? Please describe.**

Update extension to PHPUnit 10.

**Describe the solution you'd like**

Update internals to use PHPUnit 10's new Event System.

**Comment by MGatner** [comment]
Is Tachycardia compatible with PHPUnit 10 without this feature?

**Comment by paulbalandan** [comment]
I'm not sure. Haven't tried it yet.
